baseURL = "https://www.shayonkhaled.com"
languageCode = 'en-us'
title = "shayon khaled"

pagination.pagerSize = 5
[menu]
  [[menu.main]]
    name = "blogs"
    url = "/blogs"
    weight = 1

  [[menu.main]]
    name = "projects"
    url = "/projects"
    weight = 2

[params]
  description = "i build cool stuff, mostly."
  wiki = "about"
  hero = "hi, i’m **shayon**. originally from bangladesh and currently **based in japan.** studying mechatronics at kyoto university of advanced science. when bored, i tinker and **build stuff**"
  search = false
  mainSections = ["blogs"]
  projects = [
      {name = "what's for lunch?", url = "https://www.whatsforlunch.lol", description = "cafeteria menu scraper discord bot"},       
      {name = "Dynamic PID Tuning Platform", url = "https://github.com/ShayonKhaled/Dynamic-PID-Tuning-Platform", description = "test rig for tuning robomaster m3508 motors"},
      {name = "proxicharge", url = "https://github.com/ShayonKhaled/ProxiCharge", description = "proximity-based battery charger safety system."},       
  ]
  socials = [        
  {name = "github", url = "https://github.com/ShayonKhaled"},
  {name = "linkedin", url = "https://www.linkedin.com/in/shayonkhaled/"},
  ]


