baseURL = "https://shayonkhaled.github.io/websitehugo/"
languageCode = 'en-us'
title = "Shayon Khaled"

pagination.pagerSize = 5
[menu]
  [[menu.main]]
    name = "Blogs"
    url = "/blogs"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 2

[params]
  description = "I build cool stuff, mostly."
  wiki = ""
  hero = "Hi, I’m **Shayon**. Originally from Bangladesh and currently **based in Japan.** Studying mechatronics at Kyoto University of Advanced Science. When bored, I tinker and **build stuff**"
  search = false
  mainSections = ["blogs"]
  projects = [
      {name = "What's for lunch?", url = "https://www.whatsforlunch.lol", description = "Cafeteria menu scraper Discord bot"},       
      {name = "Dynamic PID Tuning Platform", url = "https://github.com/ShayonKhaled/Dynamic-PID-Tuning-Platform", description = "Test rig for tuning RoboMaster M3508 motors"},
      {name = "ProxiCharge", url = "https://github.com/ShayonKhaled/ProxiCharge", description = "Proximity-based battery charger safety system."},       
  ]
  socials = [        
  {name = "github", url = "https://github.com/ShayonKhaled"},
  {name = "linkedin", url = "https://www.linkedin.com/in/shayonkhaled/"},
  ]


